AWSTemplateFormatVersion: 2010-09-09
Description: "Sample Lamda Function using CFN"

Parameters:
  functionName:
    Type: String 
    Description: "Lamda Function Name"
    Default: "fnHelloWorldCfn"
  S3Bucket:
    Type: String 
    Description: "S3 Bucket Name where Lamda code is stored"
    Default: "mgl-trn-cfn-scripts"
  lamdaZipFile:
    Type: String 
    Description: "Lamda Zip File in the bucket lamda/ folder"
    Default: "fnHello-v0.py.zip"

Resources: 
  LogicalID:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Join ["/", ["lambda", !Ref lamdaZipFile]]
      Description: "Sample Lambda using CFN"
      FunctionName: !Ref functionName
      Handler: !Ref lamdaZipFile
      Role: !GetAtt lamdaFunctionRole.Arn # Required
      Runtime: "python3.12"
      Timeout: 60

  lamdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: 
                - "lambda.amazonaws.com" 
            Action:
                - "sts:AssumeRole"      
      Description: !Join [" ", ["IAM Role for", !Ref functionName, "lamda function"]]
      RoleName: !Join ["-", [!Ref functionName, "lamda", "role"]]
      Policies:
        - PolicyName: !Join ["-", [!Ref functionName, "execution", "policy"]]
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                Resource:
                  - "arn:aws:logs:*:*:*"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Join ["", ["arn:aws:logs:*:*:log-group:/aws/lambda/", !Ref functionName, ":*"]]